blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/TcNsmMU3tX
    about: Feel free to ask for support or have a chat with us on our Discord server!
  - name: Discussions, Q&A, ideas, show us something...
    url: https://github.com/GlowingJellyfish/GlowingJellyfish/discussions/new
    about: Do you have an idea for GlowingJellyfish? Do you want to show something that you made? Please open a discussion about it!
